### ISSUE TITLE
Handle expired session

### ISSUE THREAD

**Issue by yangzhaox** [moochee/moochee#5]
2023-11-06T17:07:50.832112470Z app[web.1]: Moochee started at 8080
2023-11-06T17:41:07.108887059Z app[web.1]: Error: did not find expected authorization request details in session, req.session["oidc:auth.moochee.us"] is undefined
2023-11-06T17:41:07.108955328Z app[web.1]:     at /app/node_modules/openid-client/lib/passport_strategy.js:132:13
2023-11-06T17:41:07.108964916Z app[web.1]:     at OpenIDConnectStrategy.authenticate (/app/node_modules/openid-client/lib/passport_strategy.js:191:5)
2023-11-06T17:41:07.108972139Z app[web.1]:     at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:369:16)
2023-11-06T17:41:07.108979984Z app[web.1]:     at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:370:7)
2023-11-06T17:41:07.108988230Z app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2023-11-06T17:41:07.108996806Z app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:144:13)
2023-11-06T17:41:07.109035779Z app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
2023-11-06T17:41:07.109045528Z app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2023-11-06T17:41:07.109053893Z app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:15
2023-11-06T17:41:07.109062309Z app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)

**Comment by yangzhaox** [comment]
a6fdda4f1770af3be61cf4c0eaa56363756c4cc6
